
name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract cross-compiler
      run: |
        wget -O x86_64-elf.tar.xz https://newos.org/toolchains/x86_64-elf-7.5.0-Linux-x86_64.tar.xz
        tar -xf x86_64-elf.tar.xz
        export PATH=$PATH:$PWD/x86_64-elf/bin

    - name: Configure (64-bit non-headered)
      run: ./configure --target=x86_64-none --disable-headers
      env:
        PATH: $PATH:$PWD/x86_64-elf/bin

    - name: Build
      run: make
      env:
        PATH: $PATH:$PWD/x86_64-elf/bin

    - name: Run checks
      run: make check
      env:
        PATH: $PATH:$PWD/x86_64-elf/bin

    - name: Run distribution checks
      run: make distcheck
      env:
        PATH: $PATH:$PWD/x86_64-elf/bin
