name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y gcc-multilib g++-multilib
    - name: Configure (64-bit non-headered)
      run: |
        ./configure --target=x86_64-none --disable-headers
    - name: Build
      run: make build
    - name: Run checks
      run: make check
    - name: Run distribution checks
      run: make distcheck
